version: "3"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PG_CONNECTION_STRING=host=postgres user=postgres password=postgres dbname=postgres port=5432 sslmode=disable
